# Generated by Django 5.0.1 on 2024-02-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings_model',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='savings_model',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
