# Generated by Django 5.0.1 on 2024-02-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application2', '0002_alter_savings_model_age_alter_savings_model_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='savings_model',
        ),
    ]
