# Generated by Django 5.0.1 on 2024-02-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savings_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField(max_length=5)),
                ('amount', models.IntegerField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
